defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:12

version: 2
jobs:
  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Tests
          command: npm t
      - run:
          name: Lint code
          command: npm run lint -- --plugin log
      - run:
          name: Set npmrc credentials
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Publish this thing
          command: npx published  --git-tag

workflows:
  version: 2
  integration:
    jobs:
      - publish:
          context: org-global
