defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:12

version: 2
jobs:
  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set npmrc credentials
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Tests
          command: npm t
      - run:
          name: Lint code
          command: npm run lint -- --plugin log
      - run:
          name: Publish this thing
          command: |
                   curl --header "Authorization: token ${GITHUB_API_TOKEN}" \
                   --header 'Accept: application/vnd.github.v3.raw' \
                   --header "User-Agent: fiverr/${CIRCLE_PROJECT_REPONAME}" \
                   https://raw.githubusercontent.com/fiverr/circleci_common/scripts/node-package/publish-public-package.sh | bash

workflows:
  version: 2
  integration:
    jobs:
      - publish:
          context: org-global
